use crate::paths::clangd_include_arg;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClangdConfigInput {
    pub msvc_include: String,
    pub sdk_includes: Vec<String>,
    pub compile_database_path: Option<String>,
}

/// Formats a YAML string value, wrapping in quotes if it contains spaces.
///
/// Note: Colons in Windows paths (like C:) don't require quotes in YAML values,
/// unless the path also contains spaces or other characters that need escaping.
fn format_yaml_value(value: &str) -> String {
    // Only add quotes when containing spaces
    // Double quotes need escaping, backslashes converted to forward slashes
    if value.contains(' ') || value.contains('"') {
        let normalized = value.replace('\\', "/").replace('"', "\\\"");
        format!("\"{}\"", normalized)
    } else {
        value.replace('\\', "/")
    }
}

pub fn render_clangd_config(input: &ClangdConfigInput) -> String {
    let mut output = String::new();
    output.push_str("# Auto-generated by Zed MSVC C++ Assistant.\n");
    output
        .push_str("# Edit this file to customize clangd behavior; plugin V0.2 will not overwrite existing .clangd.\n");

    // If compilation database exists, use it preferentially
    if let Some(db_path) = &input.compile_database_path {
        output.push_str("# Detected compile_commands.json, using compilation database.\n");
        output.push_str(
            "# Include paths, macro definitions, and compile options parsed by CMake are read from compile_commands.json.\n",
        );
        output.push_str(
            "# MSVC/Windows SDK includes serve as fallback paths for clangd to run outside VS Developer environment.\n",
        );
        output.push_str("CompileFlags:\n");
        output.push_str(&format!(
            "  CompilationDatabase: {}\n",
            format_yaml_value(db_path)
        ));
        output.push_str("  Add:\n");
    } else {
        output.push_str("CompileFlags:\n");
        output.push_str("  Compiler: clang-cl\n");
        output.push_str("  Add:\n");
    }

    output.push_str(&format!(
        "    - {}\n",
        clangd_include_arg(&input.msvc_include)
    ));

    if input.sdk_includes.is_empty() {
        output.push_str("    # Windows SDK include not auto-detected; manually add /I... if needed\n");
        output
            .push_str("    # - /IC:/Program Files (x86)/Windows Kits/10/Include/<version>/ucrt\n");
        output.push_str("    # - /IC:/Program Files (x86)/Windows Kits/10/Include/<version>/um\n");
        output.push_str(
            "    # - /IC:/Program Files (x86)/Windows Kits/10/Include/<version>/shared\n",
        );
    } else {
        for include in &input.sdk_includes {
            output.push_str(&format!("    - {}\n", clangd_include_arg(include)));
        }
    }

    output.push_str("Diagnostics:\n");
    output.push_str("  Suppress: ['pp_file_not_found']\n");
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_msvc_and_sdk_include_paths() {
        let rendered = render_clangd_config(&ClangdConfigInput {
            msvc_include: r"C:\VS\VC\Tools\MSVC\14.40.33807\include".to_string(),
            sdk_includes: vec![
                r"C:\Windows Kits\10\Include\10.0.22621.0\ucrt".to_string(),
                r"C:\Windows Kits\10\Include\10.0.22621.0\um".to_string(),
                r"C:\Windows Kits\10\Include\10.0.22621.0\shared".to_string(),
            ],
            compile_database_path: None,
        });

        assert!(rendered.contains("Compiler: clang-cl"));
        assert!(!rendered.contains("DriverMode:"));
        assert!(rendered.contains("- /IC:/VS/VC/Tools/MSVC/14.40.33807/include"));
        assert!(rendered.contains("- /IC:/Windows Kits/10/Include/10.0.22621.0/ucrt"));
        assert!(rendered.contains("- /IC:/Windows Kits/10/Include/10.0.22621.0/um"));
        assert!(rendered.contains("- /IC:/Windows Kits/10/Include/10.0.22621.0/shared"));
        assert!(!rendered.contains("Windows SDK include not auto-detected"));
    }

    #[test]
    fn renders_manual_sdk_comments_when_sdk_is_missing() {
        let rendered = render_clangd_config(&ClangdConfigInput {
            msvc_include: r"C:\VS\VC\Tools\MSVC\14.40.33807\include".to_string(),
            sdk_includes: Vec::new(),
            compile_database_path: None,
        });

        assert!(rendered.contains("- /IC:/VS/VC/Tools/MSVC/14.40.33807/include"));
        assert!(rendered.contains("Windows SDK include not auto-detected"));
        assert!(
            rendered
                .contains("# - /IC:/Program Files (x86)/Windows Kits/10/Include/<version>/ucrt")
        );
    }

    #[test]
    fn renders_compilation_database_when_present() {
        let rendered = render_clangd_config(&ClangdConfigInput {
            msvc_include: r"C:\VS\VC\Tools\MSVC\14.40.33807\include".to_string(),
            sdk_includes: Vec::new(),
            compile_database_path: Some(r"C:\project\build".to_string()),
        });

        assert!(rendered.contains("Detected compile_commands.json, using compilation database"));
        assert!(rendered.contains("Include paths, macro definitions, and compile options parsed by CMake"));
        assert!(rendered.contains("MSVC/Windows SDK includes"));
        assert!(rendered.contains("CompilationDatabase: C:/project/build"));
        assert!(!rendered.contains("Compiler: clang-cl"));
        assert!(rendered.contains("Add:"));
        assert!(rendered.contains("/IC:/VS/VC/Tools/MSVC"));
    }

    #[test]
    fn does_not_render_compilation_database_when_missing() {
        let rendered = render_clangd_config(&ClangdConfigInput {
            msvc_include: r"C:\VS\VC\Tools\MSVC\14.40.33807\include".to_string(),
            sdk_includes: Vec::new(),
            compile_database_path: None,
        });

        assert!(!rendered.contains("CompilationDatabase:"));
        assert!(!rendered.contains("Detected compile_commands.json"));
    }

    #[test]
    fn quotes_path_with_spaces() {
        let rendered = render_clangd_config(&ClangdConfigInput {
            msvc_include: r"C:\VS\VC\Tools\MSVC\14.40.33807\include".to_string(),
            sdk_includes: Vec::new(),
            compile_database_path: Some(r"C:\My Project\build output".to_string()),
        });

        assert!(rendered.contains("CompilationDatabase: \"C:/My Project/build output\""));
    }

    #[test]
    fn does_not_quote_path_without_spaces() {
        let rendered = render_clangd_config(&ClangdConfigInput {
            msvc_include: r"C:\VS\VC\Tools\MSVC\14.40.33807\include".to_string(),
            sdk_includes: Vec::new(),
            compile_database_path: Some(r"C:\project\build".to_string()),
        });

        assert!(rendered.contains("CompilationDatabase: C:/project/build"));
        assert!(!rendered.contains("CompilationDatabase: \"C:/project/build\""));
    }
}
