use crate::paths::clangd_include_arg;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClangdConfigInput {
    pub compiler: String,
    pub compile_commands_dir: String,
    pub extra_flags: Vec<String>,
    pub msvc_include: Option<String>,
    pub sdk_includes: Vec<String>,
}

/// Formats a YAML string value, wrapping in quotes if it contains spaces.
///
/// Note: Colons in Windows paths (like C:) don't require quotes in YAML values,
/// unless the path also contains spaces or other characters that need escaping.
fn format_yaml_value(value: &str) -> String {
    // Only add quotes when containing spaces
    // Double quotes need escaping, backslashes converted to forward slashes
    if value.contains(' ') || value.contains('"') {
        let normalized = value.replace('\\', "/").replace('"', "\\\"");
        format!("\"{}\"", normalized)
    } else {
        value.replace('\\', "/")
    }
}

pub fn render_clangd_config(input: &ClangdConfigInput) -> String {
    let mut output = String::new();
    output.push_str("# Auto-generated by Zed C++ Toolkit.\n");
    output.push_str("# Edit this file to customize clangd behavior.\n");
    output.push_str("CompileFlags:\n");
    output.push_str(&format!(
        "  CompilationDatabase: {}\n",
        format_yaml_value(&input.compile_commands_dir)
    ));
    output.push_str(&format!(
        "  Compiler: {}\n",
        format_yaml_value(&input.compiler)
    ));
    output.push_str("  Remove:\n");
    output.push_str("    - -fdeps-format=*\n");
    output.push_str("    - -fmodules-ts\n");
    output.push_str("    - -fmodule-mapper=*\n");

    let has_add_entries = !input.extra_flags.is_empty() || input.msvc_include.is_some();
    if has_add_entries {
        output.push_str("  Add:\n");
    }

    for flag in &input.extra_flags {
        output.push_str(&format!("    - {}\n", format_yaml_value(flag)));
    }

    if let Some(msvc_include) = &input.msvc_include {
        output.push_str(&format!("    - {}\n", clangd_include_arg(msvc_include)));
        if input.sdk_includes.is_empty() {
            output.push_str(
                "    # Windows SDK include not auto-detected; manually add /I... if needed\n",
            );
            output.push_str(
                "    # - /IC:/Program Files (x86)/Windows Kits/10/Include/<version>/ucrt\n",
            );
            output.push_str(
                "    # - /IC:/Program Files (x86)/Windows Kits/10/Include/<version>/um\n",
            );
            output.push_str(
                "    # - /IC:/Program Files (x86)/Windows Kits/10/Include/<version>/shared\n",
            );
        } else {
            for include in &input.sdk_includes {
                output.push_str(&format!("    - {}\n", clangd_include_arg(include)));
            }
        }
    }

    output.push_str("Diagnostics:\n");
    output.push_str("  Suppress: ['pp_file_not_found']\n");
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    fn msvc_input(compile_commands_dir: &str, sdk_includes: Vec<String>) -> ClangdConfigInput {
        ClangdConfigInput {
            compiler: "clang-cl".to_string(),
            compile_commands_dir: compile_commands_dir.to_string(),
            extra_flags: Vec::new(),
            msvc_include: Some(r"C:\VS\VC\Tools\MSVC\14.40.33807\include".to_string()),
            sdk_includes,
        }
    }

    #[test]
    fn renders_generic_clangd_config() {
        let rendered = render_clangd_config(&ClangdConfigInput {
            compiler: "g++".to_string(),
            compile_commands_dir: "build".to_string(),
            extra_flags: vec!["-std=c++20".to_string(), "-Iinclude".to_string()],
            msvc_include: None,
            sdk_includes: Vec::new(),
        });

        assert!(rendered.contains("# Auto-generated by Zed C++ Toolkit."));
        assert!(rendered.contains("CompilationDatabase: build"));
        assert!(rendered.contains("Compiler: g++"));
        assert!(rendered.contains("    - -std=c++20"));
        assert!(rendered.contains("    - -Iinclude"));
        assert!(!rendered.contains("Windows SDK include not auto-detected"));
    }

    #[test]
    fn omits_add_when_there_are_no_extra_flags_or_includes() {
        let rendered = render_clangd_config(&ClangdConfigInput {
            compiler: "g++".to_string(),
            compile_commands_dir: "cmake-build-debug".to_string(),
            extra_flags: Vec::new(),
            msvc_include: None,
            sdk_includes: Vec::new(),
        });

        assert!(!rendered.contains("  Add:"));
        assert!(rendered.contains("Diagnostics:\n  Suppress: ['pp_file_not_found']\n"));
    }

    #[test]
    fn removes_gcc_dependency_and_modules_flags_that_clangd_rejects() {
        let rendered = render_clangd_config(&ClangdConfigInput {
            compiler: "g++".to_string(),
            compile_commands_dir: "cmake-build-debug".to_string(),
            extra_flags: Vec::new(),
            msvc_include: None,
            sdk_includes: Vec::new(),
        });

        assert!(rendered.contains("  Remove:\n    - -fdeps-format=*\n"));
        assert!(rendered.contains("    - -fmodules-ts\n"));
        assert!(rendered.contains("    - -fmodule-mapper=*\n"));
    }

    #[test]
    fn renders_msvc_and_sdk_include_paths() {
        let rendered = render_clangd_config(&msvc_input(
            "build",
            vec![
                r"C:\Windows Kits\10\Include\10.0.22621.0\ucrt".to_string(),
                r"C:\Windows Kits\10\Include\10.0.22621.0\um".to_string(),
                r"C:\Windows Kits\10\Include\10.0.22621.0\shared".to_string(),
            ],
        ));

        assert!(rendered.contains("Compiler: clang-cl"));
        assert!(!rendered.contains("DriverMode:"));
        assert!(rendered.contains("- /IC:/VS/VC/Tools/MSVC/14.40.33807/include"));
        assert!(rendered.contains("- /IC:/Windows Kits/10/Include/10.0.22621.0/ucrt"));
        assert!(rendered.contains("- /IC:/Windows Kits/10/Include/10.0.22621.0/um"));
        assert!(rendered.contains("- /IC:/Windows Kits/10/Include/10.0.22621.0/shared"));
        assert!(!rendered.contains("Windows SDK include not auto-detected"));
    }

    #[test]
    fn renders_manual_sdk_comments_when_sdk_is_missing() {
        let rendered = render_clangd_config(&msvc_input("build", Vec::new()));

        assert!(rendered.contains("- /IC:/VS/VC/Tools/MSVC/14.40.33807/include"));
        assert!(rendered.contains("Windows SDK include not auto-detected"));
        assert!(
            rendered
                .contains("# - /IC:/Program Files (x86)/Windows Kits/10/Include/<version>/ucrt")
        );
    }

    #[test]
    fn renders_compilation_database() {
        let rendered = render_clangd_config(&msvc_input(r"C:\project\build", Vec::new()));

        assert!(rendered.contains("CompilationDatabase: C:/project/build"));
        assert!(rendered.contains("Compiler: clang-cl"));
        assert!(rendered.contains("Add:"));
        assert!(rendered.contains("/IC:/VS/VC/Tools/MSVC"));
    }

    #[test]
    fn quotes_path_with_spaces() {
        let rendered = render_clangd_config(&msvc_input(r"C:\My Project\build output", Vec::new()));

        assert!(rendered.contains("CompilationDatabase: \"C:/My Project/build output\""));
    }

    #[test]
    fn does_not_quote_path_without_spaces() {
        let rendered = render_clangd_config(&msvc_input(r"C:\project\build", Vec::new()));

        assert!(rendered.contains("CompilationDatabase: C:/project/build"));
        assert!(!rendered.contains("CompilationDatabase: \"C:/project/build\""));
    }
}
